USE sakila;

-- 1. List the number of films per category.
select film_id, category_id from film_category;
select category_id, name from category;

SELECT c.name, COUNT(fc.film_id) AS number_of_films
FROM film_category AS fc 
JOIN category c
ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY number_of_films asc
;

-- 2. Retrieve the store ID, city, and country for each store.
select * from country; -- country_id, country
select * from city; -- city_id, country_id, city
select * from address; -- district city_id district = city
select * from store; -- address_id store_id 
select * from staff; -- store_id address of staff in address_id
SELECT 
	store_id, 
    city, 
    country
FROM store 
JOIN address 
ON store.address_id = address.address_id
JOIN city 
ON address.city_id = city.city_id
JOIN country 
ON city.country_id = country.country_id
;


-- Calculate the total revenue generated by each store in dollars.
select * from payment; -- amount staff_id payment_id rental_id
select * from rental; -- rental_id  staff_id inventory_id 
select * from store; -- store_id, manager_staff_id
select * from staff; -- staff_id store_id
select * from inventory; -- inventory_id store_id

select store_id, sum(p.amount) as total_revenue
from store
join rental
on store.manager_staff_id = rental.staff_id
join payment p
on store.manager_staff_id = p.staff_id
group by store_id;

-- Determine the average running time of films for each category.
select film_id, length from film; 
select film_id, category_id from film_category;
select category_id, name from category;

SELECT 
	name as category_name,
    avg(f.length) AS average_running_time
from film f
join film_category fc
on f.film_id = fc.film_id 
JOIN category c
ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY name asc
;

-- Bonus:

-- Identify the film categories with the longest average running time.
-- Display the top 10 most frequently rented movies in descending order.
-- Determine if "Academy Dinosaur" can be rented from Store 1.

-- 8. Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' 
-- Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."